apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
spec: #configuracoes do deployment e nao do POD
  replicas: 3
  selector:
    matchLabels:
      app: hello-nginx
  template: #aqui eu uso o modelo de um POD para meu deployment criar
    metadata:
      labels:
        app: hello-nginx
    spec: #spec do meu POD
      containers:
      - name: nginx
        image: nginx:1.17-alpine
        ports:
        - containerPort: 80

        resources:
          requests:
            memory : "100Mi" #cada pod pode ter 100megas de memoria
            cpu: "200m"
          limits:
            cpu: "250m"
            memory: "200Mi"

       #montagem do volume do kubernet
        volumeMounts:
        - mountPath: /etc/nginx/conf.d #monta nesse endereco
          name: nginx-conf  #monta o volume chamado nginx-conf..
          readOnly: true


      #configuracao do nginx do configmap.yaml
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf # nome do arquivo onde vai montar o configmap